<!-- StreetSelector.vue -->
<template>
  <div class="form-group">
    <input 
      class="street-input" 
      type="text" 
      v-model="streetInput" 
      @input="search" 
      placeholder="Nom de la rue" 
    />
    <div v-if="showDropdown" class="dropdown">
      <div 
        v-for="street in filteredStreets" 
        :key="street.name"
        class="dropdown-item"
        @click="selectStreet(street)"
      >
        {{ street.name }}
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, watch, onMounted } from 'vue'

const props = defineProps({
  modelValue: {
    type: String,
    default: ''
  },
  poste: {
    type: String,
    required: true
  }
})

const emit = defineEmits(['update:modelValue'])

const streetInput = ref('')
const showDropdown = ref(false)
const streets = ref([])
const filteredStreets = ref([])

const getStreetJsonPath = (posteName) => {
  // Mapping from Poste name (from surveyQuestions) to base filename
  const nameToFileMap = {
    "L'Hermitage": "Hermitage",
    "Saint-Médard-sur-Ille": "Saint-Medard-sur-Ille",
    "Saint-Germain-sur-Ille": "Saint-Germain-sur-Ille",
    "La Poterie": "Rennes",
    "Pontchaillou": "Rennes",
    "Noyal-sur-Vilaine": "Noyal-sur-Vilaine",
    "Montreuil-sur-Ille": "Montreuil-sur-Ille",
    "Montfort-sur-Meu": "Montfort-sur-Meu",
    "Janzé": "Janze",
    "Guichen": "Guichen",
    "Châteaubourg": "Châteaubourg",
    "Chevaigné": "Chevaigné",
    "Cesson-Sévigné": "Cesson_Sévigne",
    "Bruz": "Bruz",
    "Breteil": "Breteil",
    "Betton": "Betton",
    "Servon-sur-Vilaine": "Servon-sur-Vilaine",
  };

  // Use the mapped name if it exists, otherwise use the original posteName
  let baseName = nameToFileMap[posteName] || posteName;
  
  // Ensure the final baseName is URI encoded (handles remaining accents, hyphens, etc.)
  const encodedPosteName = encodeURIComponent(baseName);
  // Construct the path using the new simpler filename structure
  return `/output_json/${encodedPosteName}.json`;
};

onMounted(async () => {
  if (!props.poste) {
    console.error('Poste prop is missing in StreetSelector');
    return;
  }
  try {
    const jsonPath = getStreetJsonPath(props.poste);
    console.log(`Fetching streets from: ${jsonPath}`);
    // Fetch directly with the potentially encoded path
    const response = await fetch(jsonPath)
    if (!response.ok) {
       // Log the URL that failed (as generated by getStreetJsonPath)
       console.error(`Failed URL: ${jsonPath}`);
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    const data = await response.json()
    streets.value = data
  } catch (error) {
    // Log the path that caused the error (as generated by getStreetJsonPath)
    const failedPath = props.poste ? getStreetJsonPath(props.poste) : 'undefined';
    console.error(`Error loading street data from ${failedPath}:`, error)
  }
})

const search = () => {
  if (streetInput.value.length < 2) {
    showDropdown.value = false
    filteredStreets.value = []
    return
  }

  filteredStreets.value = streets.value
    .filter(street => street.name && street.name.toLowerCase().includes(streetInput.value.toLowerCase()))
    .slice(0, 10)

  showDropdown.value = filteredStreets.value.length > 0
  emit('update:modelValue', streetInput.value)
}

const selectStreet = (street) => {
  streetInput.value = street.name
  emit('update:modelValue', street.name)
  showDropdown.value = false
}

watch(() => props.modelValue, (newValue) => {
  if (newValue !== streetInput.value) {
    streetInput.value = newValue
  }
})
</script>

<style scoped>
.form-group {
  position: relative;
  width: 100%;
  max-width: 600px;
  margin: 0 auto;
}

.street-input {
  width: 100%;
  padding: 10px 15px;
  font-size: 16px;
  border: none;
  border-radius: 4px;
  background-color: rgba(0, 0, 0, 0.5);
  color: white;
}

.street-input::placeholder {
  color: rgba(255, 255, 255, 0.7);
}

.street-input:focus {
  outline: none;
  background-color: rgba(0, 0, 0, 0.6);
}

.dropdown {
  position: absolute;
  top: 100%;
  left: 0;
  right: 0;
  background: white;
  border-radius: 4px;
  margin-top: 5px;
  max-height: 200px;
  overflow-y: auto;
  z-index: 1000;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
}

.dropdown-item {
  padding: 10px 15px;
  cursor: pointer;
  color: #333;
}

.dropdown-item:hover {
  background-color: #f5f5f5;
}
</style>